### ISSUE TITLE
v2 addon format

### ISSUE THREAD

**Issue by steveszc** [mainmatter/ember-simple-auth#2362]
Are there plans to update ESA to the v2 addon format?

This may be helpful:
https://github.com/NullVoxPopuli/ember-addon-migrator

**Comment by BobrImperator** [comment]
I think I can safely say we're open to this, but we'd like to first fully support Ember 4, but at the moment our test suite is blocked by ember-engines https://github.com/ember-engines/ember-engines/pull/798.

**Comment by bloemendal** [comment]
@BobrImperator that engine PR is merged. Does that also mean that you can work towards full Ember 4 support?

**Comment by BobrImperator** [comment]
Hi 👋 
We're making progress on this. Currently ESA also passes embroider and here is a draft of V2 migration https://github.com/mainmatter/ember-simple-auth/pull/2490

The only outstanding issue that doesn't depend on us is torii which recently had been moved to adopted addons and should support newer ember versions. Haven't checked it out yet  https://github.com/adopted-ember-addons/torii

**Comment by soroushysfi** [comment]
Hi! just wanted to check if waiting for v2 addon is the only way to get the latest version working with embroider.

**Comment by BobrImperator** [comment]
Yes, in order to use `staticAddonTrees` ESA would need to be a V2.
The work for migration is almost done but unfortunately it'd seem that `ember-fetch` seems to be blocking us in some way. Will need to figure out if this issue exists only for fastboot or with regular apps too.


PR: https://github.com/mainmatter/ember-simple-auth/pull/2604
Crosslink https://github.com/mainmatter/ember-simple-auth/issues/2577

**Comment by BobrImperator** [comment]
It's live! Ember-simple-auth 6.0.0 released
https://github.com/mainmatter/ember-simple-auth/issues/2577#issuecomment-1684392206
